window.$ = window.jQuery = window.jQuery = require('../news/js/jquery-3.2.1.min.js')
require('../news/js/bootstrap.min.js')
require('../news/js/popper.js')
require('../news/js/greensock/TweenMax.min')
require('../news/js/greensock/TimelineMax.min')
require('../news/js/greensock/animation.gsap.min')
require('../news/js/greensock/ScrollToPlugin.min')
require('../news/js/scrollmagic/ScrollMagic.min')
require('../news/js/OwlCarousel2-2.2.1/owl.carousel')
require('../news/js/easing/easing')
require('../news/js/parallax-js-master/parallax.min')
require('../news/js/my-js')
require('../news/js/custom')
